version: '3.3'
services:
  go-gin-blog:
    container_name: gin-blog-docker
    #image: gin_go-gin-blog
    build: ./
    ports:
      - 8080:8080
    networks:
      - go-gin-blog
#    volumes:
#      - .:/working/
#    command: go build /working/main.go
#    entrypoint: /working/main
networks:
  go-gin-blog:
